version: '3.8'
services:
  db:
    image: postgres:15
    container_name: personal_suite_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: personal_suite
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: personal_suite_backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/personal_suite
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

volumes:
  postgres_data:
